package Views;

import bll.Hond;
import dal.HondBewerkingen;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Heidi
 */
public class Toevoegen extends javax.swing.JFrame {

    private Admin admin;
    private Hond hond;

    /**
     * Creates new form desktop
     */
    public Toevoegen(Admin a) {
        initComponents();
        admin = a;
    }

    public Toevoegen(Admin a, Hond h) {
        initComponents();
        admin = a;
        hond = h;
        txtNaam.setText(h.getNaam());
        cbGeslacht.setSelectedItem(h.getGeslacht());
        txtBeschrijving.setText(h.getBeschrijving());
        txtLeeftijd.setText(Integer.toString(h.getLeeftijd()));
        txtRas.setText(h.getRas());
        txtFoto.setText(h.getFoto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaam = new javax.swing.JLabel();
        lblGeslacht = new javax.swing.JLabel();
        txtNaam = new javax.swing.JTextField();
        lblLeeftijd = new javax.swing.JLabel();
        txtLeeftijd = new javax.swing.JTextField();
        lblRas = new javax.swing.JLabel();
        txtRas = new javax.swing.JTextField();
        lblBeschrijving = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBeschrijving = new javax.swing.JTextArea();
        btnOpslaan = new javax.swing.JButton();
        cbGeslacht = new javax.swing.JComboBox<>();
        txtFoto = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNaam.setText("Naam");

        lblGeslacht.setText("Geslacht");

        lblLeeftijd.setText("Leeftijd");

        lblRas.setText("Ras");

        lblBeschrijving.setText("Beschrijving");

        txtBeschrijving.setColumns(20);
        txtBeschrijving.setRows(5);
        jScrollPane1.setViewportView(txtBeschrijving);

        btnOpslaan.setText("Opslaan");
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        cbGeslacht.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reu", "Teef" }));

        lblFoto.setText("Foto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLeeftijd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeslacht, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNaam, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBeschrijving, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpslaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFoto)
                        .addComponent(jScrollPane1)
                        .addComponent(txtRas)
                        .addComponent(txtLeeftijd)
                        .addComponent(cbGeslacht, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNaam)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaam)
                    .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeslacht)
                    .addComponent(cbGeslacht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeeftijd)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLeeftijd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeschrijving))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpslaan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        // TODO add your handling code here:
        if (txtNaam.getText().isEmpty() && txtRas.getText().isEmpty() && txtBeschrijving.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alles invullen aub.");
        } else if (hond != null) {
            HondBewerken();
        } else {
            HondToevoegen();
        }

    }//GEN-LAST:event_btnOpslaanActionPerformed

    private void HondToevoegen() {
        Hond h = new Hond();
        h.setNaam(txtNaam.getText());
        h.setBeschrijving(txtBeschrijving.getText());
        h.setRas(txtRas.getText());
        h.setFoto(txtFoto.getText());
        h.setGeslacht(cbGeslacht.getSelectedItem().toString());
        h.setLeeftijd(Integer.parseInt(txtLeeftijd.getText()));
        try {
            h.setLeeftijd(Integer.parseInt(txtLeeftijd.getText()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gelieve een getal in te geven aub.");
            return;
        }
        h.setAdopteren(false);
        HondBewerkingen.HondToevoegen(h);
        admin.VulLijst();
        dispose();
    }

    private void HondBewerken() {
        Hond h = new Hond();
        h.setNaam(txtNaam.getText());
        h.setBeschrijving(txtBeschrijving.getText());
        h.setRas(txtRas.getText());
        h.setFoto(txtFoto.getText());
        h.setGeslacht(cbGeslacht.getSelectedItem().toString());
        h.setLeeftijd(Integer.parseInt(txtLeeftijd.getText()));
        try {
            h.setLeeftijd(Integer.parseInt(txtLeeftijd.getText()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gelieve een getal in te geven aub.");
            return;
        }
        h.setAdopteren(false);
        h.setId(hond.getId());
        HondBewerkingen.HondWijzigen(h);
        admin.VulLijst();
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Toevoegen().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JComboBox<String> cbGeslacht;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBeschrijving;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblGeslacht;
    private javax.swing.JLabel lblLeeftijd;
    private javax.swing.JLabel lblNaam;
    private javax.swing.JLabel lblRas;
    private javax.swing.JTextArea txtBeschrijving;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtLeeftijd;
    private javax.swing.JTextField txtNaam;
    private javax.swing.JTextField txtRas;
    // End of variables declaration//GEN-END:variables
}
